spring:
  application:
    name: "PhotoAppApiConfigServer"
  profiles:
    active: "native"
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config/projects"
  rabbitmq:
    host: "192.168.133.132"
    port: 5672
    stream:
      username: "guest"
      password: "guest"
server:
  port: 8012
management:
  endpoints:
    web:
      exposure:
        include: "busrefresh"
