eureka:
  client:
    instance-info-replication-interval-seconds: 1
management:
  endpoint:
    gateway:
      enabled: true
server:
  port: 8082
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
