eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: true
  health:
    circuitbreakers:
      enabled: true
server:
  port: ${PORT:0}
spring:
  devtools:
    restart:
      enabled: true
  rabbitmq:
    host: localhost
    password: '{cipher}AYCqxJqm2JUxpFzVwhV7AWZK8eA1nskX60D3RvrFjvtCsfX14yhJbFTvBax/w68l9djnM+SG5oSU4WWZ+yEM7oJD9uzhWhGp759rt9pi4I3uF5/QQ0da4qagHDdgjnbyXdNj6uZLqG4kps7gmzxcjSP9vcgWKa5hExCpvCrgQnbP7cVDX2HwsiJtXTTcRfzXMxmtgDWN/7xPRA6q/1KjRt3hMGWGj+/N8thIcEA1SHC/oL4Bf5f5rA89t/ofIf/LIlb1Skfgs3TCm5eh6piTF0etmpiiGgMUJTbtzQZSvuxjpPjCPyuZOhZV4huuTcFs/fEW/YQXtSy1g76wXjveXUE0tFdGAiaLVYLU26l/TJwfG4N6qG8qQDt7IgqvDh+NNu2OJNqTPVkxEx/d8Onwg1lBS/nYMZs+diFXP7lBP2DKGZ/LeWkTZ6YeJlAuINwNCdj0Q6iWFtOFReAKwojX458B9u1KBpXgxLkjll3179u+sAEXdGpA6TBtWOwrpELPSD5rBpUgG2DqC41VK6vYMV1kjA3gk6V0YnwDqfVXurAtmg=='
    port: 5672
    username: guest
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
token:
  secret: '{cipher}AYC9xwmGmMNfQ1z8ptyc75pgiy3/6m+1R0iAXMnHBiGQmoYAWPez9DII6l1c0sfZqBosFk19vAYUP0GQIO5aGwYlJoJ7LSHKDcuRv/5ZEr0dM/Ncew77nCwTctbn/6tJJc57hLpHC2ft0QBAz3GbPrU3MeHo95puSHWHuFnrAhqMNTFRf4siUL2niSsHwIJtpemCZVsAv0OMblDX43ld/jkV8hslQCJlvDvBpDMFTCjuMgedwHoREF5NdiwqvqCjP4r3KyVY9V47QjOUl4LtRDA+zr+nGmxnTvVY9rS6sNQ9oujxmS56KjfX9d/6Y2zCcwwt2MYf2kKjxOdn69DGP6YTyzlz3bLCHc0Zy5fz8sEfxuVoDTuJCd9lB2vQsRA4/dr9rMSosgTjq/ypcoTYc1p7KqgjKPQtpAvuicusnSY/65hhY9eu9iNTLowHTHy6APx8mja9YHhMZwrXPuTfJQJQ18L0hIDwNA9i7o5af9HY8wJHy2YFgQMylxNJfUMWq3MTKnVQT47jRGEVDteMYAPvobpdqkQdVmtjvVjG0da+8peABV5VzM5rQp0KUElNizEGf1Iqx2xjIWpUKkCJg2QNbrSnNkXjn2FGfKlo5VTz8g=='
resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      albums-ws:
        registerHealthIndicator: true
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10s
        sliding-window-size: 2
        sliding-window-type: count_based
        minimum-number-of-calls: 10
        event-consumer-buffer-size: 10
  retry:
    retry-aspect-order: 2
    instances:
      albums-ws:
        max-attempts: 3
        wait-duration: 2s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 5