#logging:
#  file:
#    name: "${spring.application.name:}.log"
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
eureka:
  client:
    service-url:
      defaultZone: "{cipher}AYBKIdYArmPfvug2YbFkiMdmy1T2zVeFrAqVdmg4Oid2Ugau7tL12KwowE+H5P+browZ5pteGYRMcchZPZpfUHsVqFbAxv/KcniyJg7UDLHNyLVr3F5AvjuezCUWHJgg7uiY8P+CRWi4oLlDSwM1EFRajWuF3jPxk5kblQVBoYSOMpHN1YC0S3BPP+xMz15qlIzmrSrz1GNnlCMElmKe+SJoYGVsLsg+Fw1ZwvEG1tvR48MiAJ2MkB14oyKiPT4SKOyWBANms5NQyhgHfrltOAQyddbEODotY74I1ZAp03X6RqakG9IYjRfYgYYXaJiU7nkpzYIdNQWYcvHpUjVhdfA0yDqnXb3ExUE7tZoQfXdnRcBskh/rPyuF0HRb0AVn57wwFumQrqWoF08+0mYs/hmL2GvntTzogBXZ6k/wsamkHCsZankHm5NaHPad8/M3tSkkik43mjO9N8DQXhU42jsFsE9zwJU/djIorcNEAUMT6aqKIJgnrYU/QW6sdeWirZwQVViRXRJGbKFUkZtFGaJgi/HkizCU0BXszANpi67XNcJBV2UyqqfAWrMR4RrXsMW2Xw30ZHGM26EEWdGAbciv"
  instance:
    lease-renewal-interval-in-seconds: 5
management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: true
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1
  zipkin:
    tracing:
      endpoint: http://192.168.133.132:9411/api/v2/spans
server:
  port: ${PORT:0}
spring:
  devtools:
    restart:
      enabled: true
  rabbitmq:
    host: "192.168.133.132"
    password: '{cipher}AYCqxJqm2JUxpFzVwhV7AWZK8eA1nskX60D3RvrFjvtCsfX14yhJbFTvBax/w68l9djnM+SG5oSU4WWZ+yEM7oJD9uzhWhGp759rt9pi4I3uF5/QQ0da4qagHDdgjnbyXdNj6uZLqG4kps7gmzxcjSP9vcgWKa5hExCpvCrgQnbP7cVDX2HwsiJtXTTcRfzXMxmtgDWN/7xPRA6q/1KjRt3hMGWGj+/N8thIcEA1SHC/oL4Bf5f5rA89t/ofIf/LIlb1Skfgs3TCm5eh6piTF0etmpiiGgMUJTbtzQZSvuxjpPjCPyuZOhZV4huuTcFs/fEW/YQXtSy1g76wXjveXUE0tFdGAiaLVYLU26l/TJwfG4N6qG8qQDt7IgqvDh+NNu2OJNqTPVkxEx/d8Onwg1lBS/nYMZs+diFXP7lBP2DKGZ/LeWkTZ6YeJlAuINwNCdj0Q6iWFtOFReAKwojX458B9u1KBpXgxLkjll3179u+sAEXdGpA6TBtWOwrpELPSD5rBpUgG2DqC41VK6vYMV1kjA3gk6V0YnwDqfVXurAtmg=='
    port: 5672
    username: guest
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
token:
  secret: '{cipher}AYCnZSMrJgadf1K3UsIDq/BsiOtz4lQmch08QEU/zzg2qtlUicTZcIlkmK6lHnj5CCDJxxbKuHsgrhs7TgTZBHNwXLuwCNzwIeqkpOvl3UWh8pOJ2zBPINapYul7akJMjaJF12umaw6hAwHH0cgV4uLlNA+gvLSVHUMws7xFvT+qCVlogN5Y80/L/IoE9wFfVMeryZEFJJ1ch371hK/qOP6/ZhyR/qPfUhpTUZJPHnAluGxlCCkqBaINALFWqCG3cU/Zp59CgzjvAJ2AqRSnQM5toKswbyA9E1wweys6zJdhMdyrHs4a3pkTFOQOIos5kygpcxBen0bYQR52VUw3AwGr4YeUIIsfx5uCLWWwurLxD2a+aMUvHEdbDcHiscuSieNCwZhI49hFQsG2u7SHCxRId4Q4kslRjw9aeLMCaR8UaixXKC2OvU23ksedpvpJV35zATVCDmeulb+YgsvYur2ySKZ3RJcE28tOvObr0SAg8aTy/K1TNEU2ATGye61A8soMOGIVZVBqkm5JWhjFV6GyC2F8UR+6+OAs3KsiJ3UkiVcSWcC2KHWKN8By9Qf5IEAJsJsG8yU2EiubRN3oBVs2/1zjAzVw3wjj6XBu0/G02OA5Bo58mXDlYgC0Mwv1ujo='
resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      albums-ws:
        registerHealthIndicator: true
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10s
        sliding-window-size: 2
        sliding-window-type: count_based
        minimum-number-of-calls: 10
        event-consumer-buffer-size: 10
  retry:
    retry-aspect-order: 2
    instances:
      albums-ws:
        max-attempts: 3
        wait-duration: 2s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 5